In [1]:
#NUMPY numerical python 

In [2]:
a=[2,3,5]

In [3]:
type(a)

list

In [4]:
#speed #memory efficient #easy to use #lot of tools for maths

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
arr=np.array([[[2,3,4],[8,5,6],[3,4,2]]])

In [8]:
print(arr)

[[[2 3 4]
  [8 5 6]
  [3 4 2]]]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.size

9

In [11]:
arr.shape

(1, 3, 3)

In [12]:
arr.ndim

3

In [13]:
arr1=np.array([4,5,6,7,8])

In [14]:
print(arr1)

[4 5 6 7 8]


In [15]:
#mathematical operations + - * / %

In [16]:
print(arr1 * 10)

[40 50 60 70 80]


In [17]:
arr3=arr1 + 10

In [18]:
print(arr3)

[14 15 16 17 18]


In [19]:
a=np.array([[40, 50 ,60, 70, 80],[23,45,12,45,34]])

In [20]:
b=a/5

In [21]:
print(b)

[[ 8.  10.  12.  14.  16. ]
 [ 4.6  9.   2.4  9.   6.8]]


In [22]:
print(a)

[[40 50 60 70 80]
 [23 45 12 45 34]]


In [23]:
type(a)

numpy.ndarray

In [24]:
#Aggregate functions in numpy

In [25]:
a.sum()

np.int64(459)

In [26]:
a.min()

np.int64(12)

In [27]:
a.max()

np.int64(80)

In [28]:
a.mean()

np.float64(45.9)

In [29]:
a.std()

np.float64(19.521526579650477)

In [30]:
a.var()

np.float64(381.09000000000003)

In [31]:
#indexing and slicing

In [32]:
c=np.array([[[2,3,4,5,6],[5,6,3,2,1],[4,2,1,3,4]]])

In [33]:
c[2,0]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [ ]:
c.ndim

In [ ]:
#slicing

In [ ]:
print(c[2:])

In [ ]:
print(c[:3])

In [ ]:
print(c[::-1])

In [ ]:
c[1,2:]

In [ ]:
np.arange(1,10,2)  #start,stop,step

In [ ]:
np.arange(10,0,-2)

In [ ]:
np.zeros((5,3),dtype=int)

In [ ]:
np.eye(4,dtype=int)

In [ ]:
np.ones((2,3),dtype=int)

In [ ]:
np.full((2,3),7)

In [ ]:
np.linspace(0,1,10)

In [ ]:
np.linspace(5,100,10)

In [ ]:
np.random.rand(3,3)   #generate random number of any shape 

In [ ]:
np.random.randint(2,80,5) 

In [ ]:
e=np.array([10, 42, 25, 23,75, 55])

In [ ]:
print(e)

In [ ]:
e.reshape(2,3)

In [ ]:
c=np.array([[[2,3,4,5,6],[5,6,3,2,1],[4,2,1,3,4]]])

In [ ]:
c.ndim

In [ ]:
d=c.flatten()

In [ ]:
d.ndim

In [ ]:
print(d)

In [ ]:
arr1=np.array([2,3, 4, 5, 6, 5])

In [ ]:
arr4=np.array([23,32, 40, 5, 60, 5])

In [ ]:
arr2=np.array([20,10, 42, 54, 61, 51])

In [ ]:
arr3=np.concatenate((arr1,arr2,arr4))   #concatenate multiple arrays

In [ ]:
print(arr3)

In [ ]:
arr5=np.array([[20,10, 42, 54, 61, 51],[201,101, 421, 541, 611, 51]])

In [ ]:
np.insert(arr5,1,100,axis=0)                          #(array,index,value,axis=0 or 1)  #1 is column

In [ ]:
arr6=np.array([230,32, 40, 5, 60, 50])

In [ ]:
np.append(arr6,100)

In [ ]:
np.delete(arr6,3)

In [ ]:
print(arr6)

In [ ]:
arr6=np.array([230,32, 40, 5, 60, 50])

In [ ]:
np.vstack(arr6)

In [ ]:
np.hstack(arr6)

In [ ]:
np.sort(arr6)

In [35]:
arr7=np.array([230,32,24, 60, 50, 60, 55])

In [ ]:
np.uniquearr7)

In [ ]:
print(arr7)

In [ ]:
np.where(arr7>50)

In [36]:
arr7[arr7>50]

array([230,  60,  60,  55])